# Site Settings
title: Start Jekyll
email: taniarascia@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/"
url: "http://indscience.github.io"
twitter_username: taniarascia
github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
  permalink: /:title/
include: ['_pages']
kramdown:
  input: GFM



 
